<template>
  <div class="style-switcher">
    <div>
      <ul id="themecolors" class="m-t-20">
        <li>
          <a
            href="javascript:void(0)"
            data-skin="default-skin"
            class="default-theme"
            >1</a
          >
        </li>
        <li>
          <a href="javascript:void(0)" data-skin="red-skin" class="red-theme"
            >2</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="green-skin"
            class="green-theme"
            >3</a
          >
        </li>
        <li>
          <a href="javascript:void(0)" data-skin="blue-skin" class="blue-theme"
            >4</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="yellow-skin"
            class="yellow-theme"
            >5</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="purple-skin"
            class="purple-theme"
            >6</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="oceangreen-skin"
            class="oceangreen-theme"
            >7</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="goodgreen-skin"
            class="goodgreen-theme"
            >8</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="goodred-skin"
            class="goodred-theme"
            >9</a
          >
        </li>
        <li>
          <a
            href="javascript:void(0)"
            data-skin="blue2-skin"
            class="blue2-theme"
            >10</a
          >
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>